// TODO Implement this library.
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Dh0K7qSitV_6FABU6B64aRGc_hRjQnQ',
    appId: '1:111643212586:web:16342eb0a11eab8395fc53',
    messagingSenderId: '111643212586',
    projectId: 'blood-bank-6450e',
    authDomain: 'blood-bank-6450e.firebaseapp.com',
    storageBucket: 'blood-bank-6450e.appspot.com',
    measurementId: 'G-5S5GNTJVR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtHk2Fo7SySNeIYavqr6jVrKCwGEEpbqE',
    appId: '1:111643212586:android:4e86a05b7ea1aab395fc53',
    messagingSenderId: '111643212586',
    projectId: 'blood-bank-6450e',
    storageBucket: 'blood-bank-6450e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoOFj3nAST-Ctgz-50lgz66lL0WPwvgCY',
    appId: '1:111643212586:ios:28c9294cc425682195fc53',
    messagingSenderId: '111643212586',
    projectId: 'blood-bank-6450e',
    storageBucket: 'blood-bank-6450e.appspot.com',
    iosBundleId: 'com.example.bda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoOFj3nAST-Ctgz-50lgz66lL0WPwvgCY',
    appId: '1:111643212586:ios:28c9294cc425682195fc53',
    messagingSenderId: '111643212586',
    projectId: 'blood-bank-6450e',
    storageBucket: 'blood-bank-6450e.appspot.com',
    iosBundleId: 'com.example.bda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Dh0K7qSitV_6FABU6B64aRGc_hRjQnQ',
    appId: '1:111643212586:web:fbb840c0fcf97bcd95fc53',
    messagingSenderId: '111643212586',
    projectId: 'blood-bank-6450e',
    authDomain: 'blood-bank-6450e.firebaseapp.com',
    storageBucket: 'blood-bank-6450e.appspot.com',
    measurementId: 'G-G76G4M0HJZ',
  );

}